version: '3.8'

services:
  ml-project:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3 