name: Deploy ML Project to Azure (Docker)

on:
  push:
    branches: [ azure-deploy ]  # Docker-based Azure deployment
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to Azure with Docker'
        required: true
        default: 'azure'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/ml-project:latest

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          app-name: ml-project
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          image: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/ml-project:latest 